# Generated by Django 3.2.3 on 2021-07-20 15:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
