# Generated by Django 3.2.7 on 2021-09-15 10:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Store', '0002_alter_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductReview',
            new_name='ProductReviewModel',
        ),
    ]
