# Generated by Django 3.2.3 on 2021-08-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/img/profilo_utente_default.png', null=True, upload_to=''),
        ),
    ]
