# Generated by Django 3.2.3 on 2021-08-14 14:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Store', '0004_auto_20210814_1400'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyUser',
            new_name='Customer',
        ),
    ]
