# Generated by Django 3.2.7 on 2021-09-16 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Store', '0004_alter_productreviewmodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_waiting', to='Store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_waiting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'WaitingListModel',
            },
        ),
    ]
