# Generated by Django 3.2.3 on 2021-08-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='../static/img/profilo_utente_default.png', null=True, upload_to=''),
        ),
    ]
