# Generated by Django 3.2.3 on 2021-08-15 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0013_auto_20210815_1409'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
