# Generated by Django 3.2.3 on 2021-09-02 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0017_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
