# Generated by Django 3.2.3 on 2021-09-07 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0019_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
