# Generated by Django 3.2.3 on 2021-09-07 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0020_auto_20210907_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='zip',
        ),
    ]
