# Generated by Django 3.2.3 on 2021-09-09 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0021_auto_20210907_0902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Profile'},
        ),
    ]
