# Generated by Django 3.2.3 on 2021-09-09 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0022_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Product'},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'verbose_name_plural': 'ProductReview'},
        ),
    ]
