# Generated by Django 3.2.3 on 2021-09-06 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cartitem_line_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='updated',
        ),
    ]
