# Generated by Django 3.2.3 on 2021-08-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
