# Generated by Django 3.2.3 on 2021-09-09 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_remove_cart_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'Cart'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name_plural': 'CartItem'},
        ),
        migrations.AlterModelOptions(
            name='customerpayment',
            options={'verbose_name_plural': 'CustomerPayment'},
        ),
    ]
