# Generated by Django 3.2.3 on 2021-08-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.IntegerField(default=123456789),
        ),
    ]
